name: indic_parler_tts
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - icu=78.1=h33c6efd_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgomp=15.2.0=he0feb66_16
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.1=hf4e2dac_1
  - libstdcxx=15.2.0=h934c35e_16
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=h3c07f61_2_cpython
  - readline=8.3=h853b02a_0
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tzdata=2025c=h8577fbf_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - absl-py==2.3.1
      - argbind==0.3.9
      - asttokens==3.0.1
      - audioread==3.1.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - contourpy==1.3.2
      - cycler==0.12.1
      - decorator==5.2.1
      - descript-audio-codec==1.0.0
      - docstring-parser==0.17.0
      - einops==0.8.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - ffmpy==1.0.0
      - filelock==3.20.0
      - fire==0.7.1
      - flatten-dict==0.4.2
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - future==1.0.0
      - grpcio==1.76.0
      - git+https://github.com/huggingface/parler-tts.git
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - importlib-resources==6.5.2
      - ipython==8.37.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - julius==0.2.7
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.46.0
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markdown2==2.5.4
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.2
      - networkx==3.4.2
      - numba==0.63.1
      - numpy==2.2.6
      - packaging==25.0
      - parler-tts==0.2.2
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.1
      - pooch==1.8.2
      - prompt-toolkit==3.0.52
      - protobuf==4.25.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.23
      - pygments==2.19.2
      - pyloudnorm==0.1.1
      - pyparsing==3.2.5
      - pystoi==0.4.1
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - randomname==0.2.1
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentencepiece==0.2.1
      - six==1.17.0
      - soundfile==0.13.1
      - soxr==1.0.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tokenizers==0.20.3
      - torch==2.8.0 --index-url https://download.pytorch.org/whl/cpu
      - torch-stoi==0.2.3
      - torchaudio==2.8.0 --index-url https://download.pytorch.org/whl/cpu
      - torchvision==0.23.0 --index-url https://download.pytorch.org/whl/cpu
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.46.1
      - typing-extensions==4.15.0
      - urllib3==2.6.2
      - wcwidth==0.2.14
      - werkzeug==3.1.4
prefix: /mnt/disk1/miniforge3/envs/indic_parler_tts
