name: fastspeech_hs
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgomp=15.2.0=he0feb66_16
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.1=h0c1763c_0
  - libuuid=2.41.2=h5347b49_1
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=h3c07f61_2_cpython
  - readline=8.2=h8c095d6_2
  - tk=8.6.13=noxft_ha0e22de_103
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - antlr4-python3-runtime==4.9.3
      - asteroid-filterbanks==0.4.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - audioread==3.1.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - ci-sdr==0.0.2
      - click==8.3.1
      - configargparse==1.7.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - decorator==5.2.1
      - distance==0.1.3
      - editdistance==0.8.1
      - einops==0.8.1
      - espnet==202511
      - espnet-tts-frontend==0.0.3
      - fast-bss-eval==0.1.3
      - filelock==3.19.1
      - fonttools==4.61.0
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - g2p-en==2.1.0
      - h5py==3.15.1
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - idna==3.11
      - importlib-metadata==4.13.0
      - indic-num2words==1.3.2
      - indic-unified-parser==1.0.6
      - inflect==7.5.0
      - jaconv==0.4.1
      - jamo==0.4.1
      - jinja2==3.1.6
      - joblib==1.5.2
      - kaldiio==2.18.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - librosa==0.11.0
      - lightning==2.6.0
      - lightning-utilities==0.15.2
      - llvmlite==0.46.0
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - networkx==3.3
      - nltk==3.9.2
      - noisereduce==3.0.3
      - numba==0.63.0
      - numpy==2.1.2
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - platformdirs==4.5.1
      - pooch==1.8.2
      - propcache==0.4.1
      - protobuf==6.33.2
      - pycparser==2.23
      - pyparsing==3.2.5
      - pypinyin==0.44.0
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.6.0
      - pytz==2025.2
      - pyworld==0.3.5
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentencepiece==0.2.0
      - setuptools==73.0.1
      - six==1.17.0
      - soundfile==0.13.1
      - soxr==1.0.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.8.0 --index-url https://download.pytorch.org/whl/cpu
      - torch-complex==0.4.4
      - torchaudio==2.8.0 --index-url https://download.pytorch.org/whl/cpu
      - torchmetrics==1.8.2
      - torchvision==0.23.0 --index-url https://download.pytorch.org/whl/cpu
      - tqdm==4.67.1
      - typeguard==4.4.4
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - unidecode==1.4.0
      - urllib3==2.6.1
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/ritik-intel/miniforge3/envs/fastspeech_hs
